kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-access
  namespace: default
subjects:
- kind: User
  name: test
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: pod-access
  apiGroup: ""
  subjects:
- kind: ServiceAccount
  name: api-service-account
  namespace: default

