kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-access
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-access
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: api-service-account
  namespace: default
